---
title: "R Notebook"
output: html_notebook
---

Se realiza un análisis exploratorio

```{r}


```


```{r}
rm(list=ls())

# Librer?a
library(tidymodels)
library(readxl)
library(fastDummies)
library(brms)
library(nycflights13)
library(DataExplorer)


datos <- read_excel("C:/Users/peter/OneDrive - ITESO/Documents/School Work/Maestría Data Science/Optimización Convexa/Dataset entradas/datos_cuchareados.xlsx")

introduce(datos)
plot_intro(datos)
```


```{r}
# Librer?a fastDummies para convertir variables a dummy y quitar 1 categor?a de cada variable.
datos_dummy <- dummy_cols(datos,  select_columns = c("Marca", "Diseño"),remove_first_dummy = TRUE)

#Limpiar datos para quitar variables repetidas o que no se van a usar 
datos_dummy1 <- subset(datos_dummy,select=-c(RES,Marca,Diseño))

#Renombrar la primera columna
names(datos_dummy1)[1] <- "Y"

# Normalizamos
#datos_dummy1$Precio <- datos_dummy1$Precio/100

datos_dummy1 <- data.frame(datos_dummy1)



# modelo bernoulli
fit <- brm(Y ~ Diseño_Del_mundial+
             Precio+
             Marca_Gaser+
             Diseño_Fondo_blanco+
             Marca_Molten+
             Marca_Voit +
             Diseño_Colorido+
             Diseño_Con_temática,
           data = datos_dummy1, 
           family = bernoulli(link = "logit"), 
           silent=TRUE, 
           refresh = -1,
           prior = c(set_prior("normal(-1,1)", class="b", coef="Marca_Gaser"), 
                     set_prior("normal(1, 1)", class="b", coef="Marca_Voit"), 
                     set_prior("normal(0, 1)", class="b", coef="Marca_Molten"), 
                     set_prior("normal(1, 1)", class="b", coef="Precio")), 
)

summary(fit)
```


Magnolia
```{r}
loss <- function(price){
  # First Create the input data to predict with out model - we want to predict whether or not our phone will sell
  our.ball <- data.frame(Diseño_Del_mundial=0,
                            Precio=price,
                            Marca_Gaser=0,
                            Diseño_Fondo_blanco=1,
                            Marca_Molten=0,
                            Marca_Voit=1,
                            Diseño_Colorido=0,
                            Diseño_Con_temática=0
                            ) 
  
  # Next, for each posterior sample from out model, predict whether or not our phone would sell at the given price. This will give a vector of 0's and 1's, did the phone sell in each posterior sample. Think of each posterior sample as a simulation. 
  pp <- posterior_predict(fit, newdata=our.ball)
  
  # Next calculate the expected return for each of these posterior simulations
  mean(pp*price)
}

(op <- optim(500,function(x)-loss(x)))
```


Hola
```{r}
x <- 90:1000 # Listing prices to evaluate
l <- sapply(x, loss) 
plot(x, l, xlab = "Listing Price", ylab = "Expected Return")


```

